### ISSUE TITLE
Test will try to use docker, even when told not to....

### ISSUE THREAD

**Issue by NL66278** [nsidnev/fastapi-realworld-example-app#192]
I created a local database that can be approached with ident authentication.

Then in .env specified:
DB_CONNECTION=postgresql+psycopg2:///real_world_application

In an ipython shell I verified that I can use this string to the database.

Still `$ USE_LOCAL_DB_FOR_TEST=True pytest` results in:
```

During handling of the above exception, another exception occurred:
../../../.cache/pypoetry/virtualenvs/fastapi-realworld-example-app-qr8Xy3u9-py3.8/lib/python3.8/site-packages/docker/api/client.py:214: in _retrieve_server_version
    return self.version(api_version=False)["ApiVersion"]
../../../.cache/pypoetry/virtualenvs/fastapi-realworld-example-app-qr8Xy3u9-py3.8/lib/python3.8/site-packages/docker/api/daemon.py:181: in version
    return self._result(self._get(url), json=True)
../../../.cache/pypoetry/virtualenvs/fastapi-realworld-example-app-qr8Xy3u9-py3.8/lib/python3.8/site-packages/docker/utils/decorators.py:46: in inner
    return f(self, *args, **kwargs)
../../../.cache/pypoetry/virtualenvs/fastapi-realworld-example-app-qr8Xy3u9-py3.8/lib/python3.8/site-packages/docker/api/client.py:237: in _get
    return self.get(url, **self._set_request_timeout(kwargs))
../../../.cache/pypoetry/virtualenvs/fastapi-realworld-example-app-qr8Xy3u9-py3.8/lib/python3.8/site-packages/requests/sessions.py:555: in get
    return self.request('GET', url, **kwargs)
../../../.cache/pypoetry/virtualenvs/fastapi-realworld-example-app-qr8Xy3u9-py3.8/lib/python3.8/site-packages/requests/sessions.py:542: in request
    resp = self.send(prep, **send_kwargs)
../../../.cache/pypoetry/virtualenvs/fastapi-realworld-example-app-qr8Xy3u9-py3.8/lib/python3.8/site-packages/requests/sessions.py:655: in send
    r = adapter.send(request, **kwargs)
../../../.cache/pypoetry/virtualenvs/fastapi-realworld-example-app-qr8Xy3u9-py3.8/lib/python3.8/site-packages/requests/adapters.py:498: in send
    raise ConnectionError(err, request=request)
E   requests.exceptions.ConnectionError: ('Connection aborted.', FileNotFoundError(2, 'No such file or directory'))
```
(Lots of the above...)

**Comment by nsidnev** [comment]
@NL66278 hi! I just merged #203 PR which completly drops docker DB from tests (actually wanted to do this a long time ago). Could you make sure that everything is all right in your case now?

**Comment by NL66278** [comment]
@nsidnev Thanks a lot. I already got everything running with this in my .env:
`DB_CONNECTION=postgresql:///real_world_application`.

But tests where still failing. Later today I will run the new code to see how that turns out.

**Comment by NL66278** [comment]
@nsidnev I can confirm that tests are running well now!

**Comment by nsidnev** [comment]
Awesome! Then I'll close this issue. Thanks for the confirmation!
